Correct Chinese and Japanese translations
weisJ/darklaf pull request #299
Opened 2022-01-07 12:40 UTC by Xujiayao

Thank you for making such a fantastic Swing Look and Feel! I corrected some Chinese and Japanese translation errors. 

Btw, I cannot find the Chinese and Japanese translation files of `theme_settings.properties`. Is it to copy the original files directly and rename the new ones to `_zh` and `_ja`? If so, please tell me, don't merge the pull request for now, I will translate them too.

Thank you!

2022-01-07 18:57 UTC, weisJ commented
Thanks for fixing the translations.

> Btw, I cannot find the Chinese and Japanese translation files of theme_settings.properties. Is it to copy the original files directly and rename the new ones to _zh and _ja?

That is correct :)

2022-01-08 05:30 UTC, Xujiayao commented
Added Chinese and Japanese translations for `theme_settings.properties`. It's ready to merge now :D

2022-01-08 17:31 UTC, weisJ requested changes

2022-01-08 17:31 UTC, weisJ commented on core/src/main/resources/com/github/weisj/darklaf/task/darklaf_ja.properties
> -Labels.colorChooser                = カラーチューザー
Please squash those changes into the first commit :)
Same applies for the changes in `darklaf_zh` and `tabFrame_ja`

2022-01-08 17:31 UTC, weisJ commented on core/src/main/resources/com/github/weisj/darklaf/task/tabFrame_ja.properties
> -popup.moveTo.south_west = 左下隅
Please squash this commit into the previous one :)

2022-01-08 18:05 UTC, Xujiayao commented
Sorry for being unfamiliar with Pull requests and Git squash, it's now a single commit. 😂

2022-01-08 19:31 UTC, weisJ commented
No worries :) Thanks a lot for the translations

2022-01-08 19:31 UTC, merged