Verticle line through table
weisJ/darklaf pull request #329
Opened 2022-08-30 02:17 UTC by tyro668

table height cannot be grid height, it will through the table.

2022-08-31 09:58 UTC, weisJ commented
Could you please elaborate what precisely the issue being fixed is here?

2022-09-08 02:46 UTC, tyro668 commented
> 

if use JTable inside with a scrollpane,the table‘s vertical lines are not end at the last row,in fact the vertical tables grid lines though the last row,like this image:

https://github.com/tyro668/pictures/blob/main/Xnip2022-09-08_10-45-34.png

2022-09-08 20:17 UTC, weisJ commented
The way the vertical lines are painted is intentional. If you think there should be an option to change that behaviour, please file a feature request issue. I highly appreciate any contributions, but would like them to be discussed beforehand if they do more than simply changing something trivial (like translations etc.). In this case I think adding an option to to change the painting behaviour through a client property would be very reasonable (similar to `TableConstants.KEY_ALTERNATE_ROW_COLOR `).

Note that
1. The height of the cells doesn't need to be computed as it is already available above as the bottom coordinate of `maxCell`.
2. As is your patch doesn't work when dragging columns

2022-09-13 10:29 UTC, tyro668 commented
Fix the problem,add property:TableConstants.KEY_VERTICAL_LINES_THROUGH

2022-09-30 11:51 UTC, weisJ requested changes
If we go forward with this change, then the value should be initialized in `installDefaults` by using a value exposed in `table.properties`.

Besides that I was wondering whether https://docs.oracle.com/javase/7/docs/api/javax/swing/JTable.html#setFillsViewportHeight(boolean) would solve your particular issue. In this case the fay to move forward would be to respect the value set by the user.

2022-09-30 11:51 UTC, weisJ commented on core/src/main/java/com/github/weisj/darklaf/ui/table/TableConstants.java
> +    String KEY_VERTICAL_LINES_THROUGH = "throughVerticalLines";
```suggestion
    String KEY_FULL_HEIGHT_VERTICAL_LINES = "Table.fullHeightVerticalLines";
```

2022-09-30 11:51 UTC, weisJ commented on core/src/main/java/com/github/weisj/darklaf/ui/table/DarkTableUI.java
> +            int tableHeight = PropertyUtil.getBooleanProperty(table, KEY_VERTICAL_LINES_THROUGH, false) ? maxCell.y + maxCell.height - minCell.y : table.getHeight();
```suggestion
            int tableHeight = PropertyUtil.getBooleanProperty(table, KEY_FULL_HEIGHT_VERTICAL_LINES, false) ? maxCell.y + maxCell.height - minCell.y : table.getHeight();
```

2022-09-30 11:51 UTC, weisJ commented on core/src/main/java/com/github/weisj/darklaf/ui/table/DarkTableUI.java
> +            int y2 = PropertyUtil.getBooleanProperty(table, KEY_VERTICAL_LINES_THROUGH, false) ? maxCell.y + maxCell.height - minCell.y : y1 + tableHeight;
```suggestion
            int y2 = PropertyUtil.getBooleanProperty(table, KEY_FULL_HEIGHT_VERTICAL_LINES, false) ? maxCell.y + maxCell.height - minCell.y : y1 + tableHeight;
```

2023-05-28 16:21 UTC, closed without merging